apiVersion: v1
kind: Pod
metadata:
  name: {{ include "mtest.fullname" . }}
  labels:
    {{- include "mtest.labels" . | nindent 4 }}
spec:
  containers:
    - name: {{ .Values.container.name }}
      image: {{ .Values.container.image }}
      ports:
        - containerPort: {{ .Values.container.port }}