apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ default "none" .Values.service.label }}-{{ .Values.serviceEnv }}
  name: {{ default "none" .Values.service.name }}-{{ .Values.serviceEnv }}
  namespace: {{ default "none" .Values.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.selector }}-{{ .Values.serviceEnv }}
